### ISSUE TITLE
V3.08 - Current Playlist is blank

### ISSUE THREAD

**Issue by PatrickGaul** [Tgxcorporation/skin.chroma#1]
Hello.  I just upgraded to V3.08 of Chroma in Kodi 1.0 RC3.  Great work!

One issue I noticed though: I select a saved playlist (an M3U file) and can play it no problem.  But whenever I select "Current Playlist" from the left menu, the playlist screen is empty.

This is definitely a Chroma issue...when I switch to the default skin (Estuary) and select "Go to Playlist", the display works fine.  Here's what I mean:

![01 - chroma - open playist display](https://cloud.githubusercontent.com/assets/12144123/22169642/82d27228-df2a-11e6-8e72-2c07ea129f23.jpg)
![02 - chroma - select current playlist](https://cloud.githubusercontent.com/assets/12144123/22169646/82deae76-df2a-11e6-9a1c-8a69b60e2ca4.jpg)
![03 - chroma - current playlist display](https://cloud.githubusercontent.com/assets/12144123/22169641/82d1ffd2-df2a-11e6-8cb2-b9c901e92969.jpg)
![04 - estuary - open playlist display](https://cloud.githubusercontent.com/assets/12144123/22169643/82d58760-df2a-11e6-99bc-417e8f8f5600.jpg)
![05 - estuary - go to playlist](https://cloud.githubusercontent.com/assets/12144123/22169644/82d8e7ac-df2a-11e6-81eb-1b0877a1f5bd.jpg)
![06 - estuary playlist display](https://cloud.githubusercontent.com/assets/12144123/22169645/82dc1b5c-df2a-11e6-9284-ad862146b213.jpg)

**Comment by Tgxcorporation** [comment]
Should be fixed now! 

Thanks

**Comment by PatrickGaul** [comment]
Fantastic!  Just tested it and it works fine.  Thanks for the rapid response!
