### ISSUE TITLE
Chroma is currently not working with Kodi Leia (Android)

### ISSUE THREAD

**Issue by niwi-hh** [Tgxcorporation/skin.chroma#4]
When I started Kodi this morning the default skin was chosen instead of Chroma. It seams It seems this is the result of a new RC if Kodi 18 at least in Android. I had to change the required xbmc.gui to version 5.14.0 instead of 5.13.0 in plugin.xml. Afterwards Chroma worked again.

**Comment by nineteen0815** [comment]
thx works

**Comment by Tgxcorporation** [comment]
I’m going to post an update for the final Leia version

**Comment by trenst** [comment]
I love Chroma skin, and now that I've updated to Leia, it was disabled.  I'm also looking forward to using it again.  Thanks.

**Comment by trenst** [comment]
I just followed the instructions [here](https://github.com/Tgxcorporation/skin.chroma/wiki/Install-from-GitHub) to install manually, and it's working great in the latest version of Kodi.  Thanks again.

**Comment by Tgxcorporation** [comment]
It's working with the latest commit.
